# Generated by Django 3.2.7 on 2022-03-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='added',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
