# Generated by Django 4.0.6 on 2022-07-29 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='added_clients', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
