# Generated by Django 3.2.7 on 2022-03-20 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_client_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='added',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
