# Generated by Django 3.2.7 on 2022-04-20 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_client_added'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctor',
            new_name='Employee',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='doctor',
            new_name='employee',
        ),
    ]
