# Generated by Django 3.2.7 on 2022-04-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_employee_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='color',
            field=models.CharField(max_length=7),
        ),
    ]
