# Generated by Django 4.0.6 on 2022-08-03 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_employee_is_in_employee_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='employees', to='home.theme'),
        ),
    ]
