# Generated by Django 4.0.5 on 2022-06-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_employee_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_in',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_out',
            field=models.DateField(null=True),
        ),
    ]
