# Generated by Django 4.2.9 on 2024-03-06 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_employee_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='second_clinic_theme',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.RESTRICT, related_name='employees_second_clinic', to='home.theme'),
        ),
        migrations.AddField(
            model_name='visit',
            name='clinic',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='employees_first_clinic', to='home.theme'),
        ),
    ]
