# Generated by Django 4.0.5 on 2022-06-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_client_added_alter_employee_date_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='price',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
