# Generated by Django 4.0.6 on 2022-07-13 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_holiday_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='visits', to='home.employee'),
        ),
    ]
